////////////////////////////////////////////////////////////////////////////////
// Copyright (C) 2013-2024 Efinix Inc. All rights reserved.
// Full license header bsp/efinix/EfxSapphireSoc/include/LICENSE.MD
////////////////////////////////////////////////////////////////////////////////

//HPS Device Config Ti375C529

#ifndef DEV_CONFIG
#define DEV_CONFIG

//TSE MAC Related 
#define TSEMAC_BASE 		 0xe9100000
#define TSEMAC_DMASG_BASE	 IO_APB_SLAVE_2_INPUT
#define TSE_DMASG_RX_CH		 0
#define TSE_RX_INTR			 SYSTEM_PLIC_USER_INTERRUPT_B_INTERRUPT
#define TSE_DMASG_TX_CH		 1
#define TSE_TX_INTR			 SYSTEM_PLIC_USER_INTERRUPT_C_INTERRUPT
#define PHY_ADDR   			 0x0
#define SUPPORT_ETH_HOT_PLUG 0

//RTC - PCF8523
#define RTC_PCF8523_SUPPORT  1
#define RTC_I2C_BASE_ADDR    SYSTEM_I2C_1_IO_CTRL

//Temp Sensor - EMC1413
#define EMC1413_SUPPORT      1
#define TEMP_SENSOR_I2C_BASE_ADDR SYSTEM_I2C_1_IO_CTRL

//SDHC
#define SDHC_BASE			0xe9000000
#define SDHC_INTERRUPT		SYSTEM_PLIC_USER_INTERRUPT_D_INTERRUPT

//ISP
#define ISP_DMA_BASE 		IO_APB_SLAVE_0_INPUT
#define ISP_DMA_INTERRUPT 	SYSTEM_PLIC_USER_INTERRUPT_A_INTERRUPT
#define ISP_AXI4_SLAVE_BASE (SYSTEM_AXI_A_BMB+0x1200000)
#define I2C_CTRL_HZ         SYSTEM_CLINT_HZ
#define ISP_CAM_APB3 		IO_APB_SLAVE_1_INPUT
#define I2C_CTRL_MIPI		SYSTEM_I2C_0_IO_CTRL

//Resolution of Display
#define FRAME_WIDTH         1920
#define FRAME_HEIGHT        1080

//Camera
//Define the picam version. By default is set to Picam V3.
//Ti375C529 do not support PicamV2.
#define PICAM_VERSION 		3

//For BSP Compatibility
#ifndef BSP_PLIC_CPU_1
#define BSP_PLIC_CPU_1      SYSTEM_PLIC_SYSTEM_CORES_1_EXTERNAL_INTERRUPT
#endif // BSP_PLIC_CPU_1

#ifndef configMTIME_BASE_ADDRESS
#define configMTIME_BASE_ADDRESS        (BSP_CLINT + 0xBFF8)
#endif // configMTIME_BASE_ADDRESS

#ifndef configMTIMECMP_BASE_ADDRESS
#define configMTIMECMP_BASE_ADDRESS     (BSP_CLINT + 0x4000)
#endif // configMTIMECMP_BASE_ADDRESS

#ifndef configCPU_CLOCK_HZ
#define configCPU_CLOCK_HZ              ( ( uint32_t ) ( BSP_CLINT_HZ ) )
#endif // configCPU_CLOCK_HZ

#ifndef BSP_LED_GPIO
#define BSP_LED_GPIO                    SYSTEM_GPIO_0_IO_CTRL
#endif // BSP_LED_GPIO

#ifndef BSP_LED_MASK
#define BSP_LED_MASK                    0xf
#endif // BSP_LED_MASK

#ifdef SYSTEM_PLIC_SYSTEM_UART_0_IO_INTERRUPT
#undef SYSTEM_PLIC_SYSTEM_UART_0_IO_INTERRUPT
#define SYSTEM_PLIC_SYSTEM_UART_0_IO_INTERRUPT SYSTEM_PLIC_USER_INTERRUPT_I_INTERRUPT
#endif 

#ifdef SYSTEM_PLIC_SYSTEM_SPI_0_IO_INTERRUPT
#undef SYSTEM_PLIC_SYSTEM_SPI_0_IO_INTERRUPT
#define SYSTEM_PLIC_SYSTEM_SPI_0_IO_INTERRUPT SYSTEM_PLIC_USER_INTERRUPT_L_INTERRUPT
#endif

#ifdef SYSTEM_PLIC_SYSTEM_SPI_1_IO_INTERRUPT
#undef SYSTEM_PLIC_SYSTEM_SPI_1_IO_INTERRUPT
#define SYSTEM_PLIC_SYSTEM_SPI_1_IO_INTERRUPT SYSTEM_PLIC_USER_INTERRUPT_M_INTERRUPT
#endif

#ifdef SYSTEM_PLIC_SYSTEM_I2C_0_IO_INTERRUPT
#undef SYSTEM_PLIC_SYSTEM_I2C_0_IO_INTERRUPT
#define SYSTEM_PLIC_SYSTEM_I2C_0_IO_INTERRUPT SYSTEM_PLIC_USER_INTERRUPT_J_INTERRUPT
#endif

#ifdef SYSTEM_PLIC_SYSTEM_I2C_1_IO_INTERRUPT
#undef SYSTEM_PLIC_SYSTEM_I2C_1_IO_INTERRUPT
#define SYSTEM_PLIC_SYSTEM_I2C_1_IO_INTERRUPT SYSTEM_PLIC_USER_INTERRUPT_K_INTERRUPT
#endif

#ifdef SYSTEM_PLIC_SYSTEM_GPIO_0_IO_INTERRUPTS_0
#undef SYSTEM_PLIC_SYSTEM_GPIO_0_IO_INTERRUPTS_0
#define SYSTEM_PLIC_SYSTEM_GPIO_0_IO_INTERRUPTS_0 SYSTEM_PLIC_USER_INTERRUPT_N_INTERRUPT
#endif

#ifdef SYSTEM_PLIC_SYSTEM_GPIO_0_IO_INTERRUPTS_1
#undef SYSTEM_PLIC_SYSTEM_GPIO_0_IO_INTERRUPTS_1
#define SYSTEM_PLIC_SYSTEM_GPIO_0_IO_INTERRUPTS_1 SYSTEM_PLIC_USER_INTERRUPT_O_INTERRUPT
#endif


#endif
